### ISSUE TITLE
Repo Webhook setup

### ISSUE THREAD

**Issue by Ugarz** [Fransgenre/administrans#15]
The main idea is to use the Mattermost webhook to push creations and updates on issues tickets and also for Pull Requests. We will be able to track issues right in the chat with links related to it.

**Comment by agateblue** [comment]
I'll look into installing https://github.com/mattermost/mattermost-plugin-github on our Mattermost server

**Comment by agateblue** [comment]
We've moved outside mattermost, I'm  closing this :)
