### ISSUE TITLE
Template de requête RGPD

### ISSUE THREAD

**Issue by codeurimpulsif** [Fransgenre/administrans#38]
Je pose l'idée ici car je me demande s'il serait utile d'ajouter un template de document (mail et lettre) pour faire une requête RGPD dans certaines conditions.

Je pense par exemple au cas du titre de civilité qui ne fait pas partie de l'état civil et qu'on peut demander à changer sans preuve juridique.

Je ne sais pas si les documents actuellement produits par Administrans sont considérés comme tel. Ni si la citation du Défenseur Des Droits est suffisante dans tous les cas.

**Comment by agateblue** [comment]
On a [un doc](https://administrans.fr/documents/demande-maj) qui permet de faire une demande de mise à jour de prénom, civilité ou les deux. Par défaut, on ne mentionne que le DDD mais il y a une case cochable pour rajouter une mention explicite de saisie du DDD et de la CNIL a défaut de réponse. Est-ce que tu pense que ça répond au besoin exprimé ?

**Comment by codeurimpulsif** [comment]
Ah je n'avais pas fait attention à ça.

Je suppose que ça suffit actuellement oui. Je ne sais pas trop s'il y a beaucoup d'aller-retours nécessaires avec ces mails, j'ai tendance aussi à envoyer du RGPD directement car il impose un délai légal de 1 mois là où la formulation `Faute d’une rapide modification` laisse peut-être la définition de "rapide" à la personne qui va lire le mail.

Mais pour le moment si personne n'a de soucis avec ça je pense que ce n'est pas nécessaire, merci !

**Comment by agateblue** [comment]
> Je suppose que ça suffit actuellement oui. Je ne sais pas trop s'il y a beaucoup d'aller-retours nécessaires avec ces mails

D'expérience ça va être du cas par cas selon les services. Des fois tu tombes sur une personne compétente et la modif est faite en 15 minutes après réception, des fois ça demande des justificatifs ou des allers-retours alors qu'il n'y a pas besoin, ou ça refuse parce que "c'est pas possible" et faut sortir les menaces et insister.

Je vais fermer le ticket, évidemment n'hésite pas à rouvrir si tu constate qu'une autre version (par exemple mentionnant le délai d'un mois de la CNIL) marchent mieux à l'usage :)
