### ISSUE TITLE
Remplacer "Tribunal de Grande Instance" par "Tribunal Judiciaire"

### ISSUE THREAD

**Issue by Kryfulli** [Fransgenre/administrans#39]
Hello,

Les TGI ayant été fusionnés aux Tribunaux Judiciaires, il est nécessaire de changer le modèle de document pour CEC au tribunal.

Il y en a en tout [deux résultats](https://github.com/search?q=repo%3AFransgenre%2Fadministrans+%22tribunal+de+grande+instance%22&type=code) pour "tribunal de grande instance" dans le repo, tous les deux dans le modèle du CEC au Tribunal:

- le premier [ligne 126](https://github.com/Fransgenre/administrans/blob/main/src/documents-templates/RequeteCecTribunal.vue#L126), qui ne doit pas être modifié car c'est une citation
- le second [ligne 244](https://github.com/Fransgenre/administrans/blob/main/src/documents-templates/RequeteCecTribunal.vue#L244), qui doit être modifié par "Tribunal de Judiciaire"

Je peux me charger de faire la PR si c'est ok.

**Comment by agateblue** [comment]
Ça me semble nickel comme proposition, merci d'avoir pris le temps de poser tout ça a plat. Si tu fais la PR je validerai ça dans la foulée :)
