### ISSUE TITLE
Erreur d'orthographe dans le footer du formulaire de changement de prénom(s) en mairie

### ISSUE THREAD

**Issue by Kryfulli** [Fransgenre/administrans#44]
Dans l'encadré tout en bas du formulaire, il est marqué "formuliaire" au lieu de "formulaire".

![image](https://github.com/Fransgenre/administrans/assets/46534294/1f5d298a-d9ed-4f02-9289-7845f94945d2)

**Comment by agateblue** [comment]
Merci d'avoir pris le temps de corriger ça. Pour les petites corrections comme celles ci qui ne nécessitent pas de discussions, c'est complètement okay de ne pas ouvrir d'issue et de proposer directement une correction comme tu as fait ensuite :)
