### ISSUE TITLE
Parcours mention de sexe puis prénom en deux fois

### ISSUE THREAD

**Issue by chitochi** [Fransgenre/administrans#46]
Dans la première section « Changer d'état civil » il est écrit «  Il est possible de changer de prénom(s) sans changer de mention de sexe, **et inversement**.  ».

Mais dans le `select` permettant de choisir son parcours, il y a « Prénom puis mention de sexe en deux fois » mais pas « Mention de sexe puis prénom en deux fois ».

Vu que je ne connais pas du tout le sujet je ne sais pas si c’est la même chose (et donc si rajouter « et inversement » au nom du parcours est envisageable, ou bien si l’ajout d’un troisième parcours serait intéressant).

Je peux faire une PR, mais je ne sais pas du tout ce qu’il faut faire (ou pas).

(Merci beaucoup pour Administrans, ça m’aide beaucoup. :purple_heart:)

**Comment by agateblue** [comment]
> Vu que je ne connais pas du tout le sujet je ne sais pas si c’est la même chose (et donc si rajouter « et inversement » au nom du parcours est envisageable, ou bien si l’ajout d’un troisième parcours serait intéressant).

Tiens c'est vrai que je n'avais jamais pensé à ce sens là en termes de parcours !

Je peux évidemment me tromper mais je pense que si l'objectif de départ est un changement de mention de sexe et de prénom, le faire en deux fois en commençant par la partie tribunal n'apporte pas grand chose hormis la complexité : quitte à faire une requête au tribunal en premier, autant demander le changement de prénom dans la foulée dans la même requête, ça réduira les délais administratifs par rapport à faire le changement de prénom en mairie.

Par contre, je peux effectivement imaginer des situations ou une personne souhaite garder son prénom et demande donc un changement de sexe, et quelques temps plus tard, décide de changer de prénom et passe donc par la procédure en mairie. À ma connaissance, rien ne l'interdit ni ne l'empèche en pratique.

Peut-être que l'on peut changer le wording du sélecteur avec quelque chose comme « Prénom et mention de sexe indépendamment » pour clarifier qu'il n'y a pas d'ordre imposé ?

**Comment by agateblue** [comment]
Fermé via #47

**Comment by agateblue** [comment]
C'est en prod -> https://administrans.fr/cec/, merci !
